defmodule Style do
  def edit(:integer, chars), do:  "<a style='color:#2a6edb;'>#{chars}</a>"
  def edit(:float, chars), do:  "<a style='color:#2a6edb;'>#{chars}</a>"
  def edit(:hexadecimal, chars), do:  "<a style='color:#2a6edb;'>#{chars}</a>"
  def edit(:octal, chars), do:  "<a style='color:#2a6edb;'>#{chars}</a>"
  def edit(:unicode_point, chars), do:  "<a style='color:#2a6edb;'>#{chars}</a>"
  def edit(:atom, chars), do: "<a style='color:aquamarine;'>#{chars}</a>"
  def edit(:single_quoted_atom, chars), do:  "<a style='color:aquamarine;'>#{chars}</a>"
  def edit(:double_quoted_atom, chars), do:  "<a style='color:aquamarine;'>#{chars}</a>"
  def edit(:keyword_atom, chars), do:  "<a style='color:#2a6edb;'>#{chars}</a>"
  def edit(:string, chars), do:  "<a style='color:greenyellow;'>#{chars}</a>"
  def edit(:multiline_string, chars), do:  "<a style='color:greenyellow;'>#{chars}</a>"
  def edit(:charlist, chars), do:  "<a style='color:greenyellow;'>#{chars}</a>"
  def edit(:multiline_charlist, chars), do:  "<a style='color:greenyellow;'>#{chars}</a>"
  def edit(:delimiter, chars), do: "<a style='color:red;'>#{chars}</a>"
  def edit(:variable, chars), do: "<a style='color:sandybrown;'>#{chars}</a>"
  def edit(:hidden_variable, chars), do:  "<a style='color:grey;'>#{chars}</a>"
  def edit(:alias, chars), do: "<a style='color:gold;'>#{chars}</a>"
  def edit(:comment, chars), do: "<a style='color:grey;'>#{chars}</a>"
  def edit(:newline, _), do:  "<div>\n</div>"
  def edit(:skip, chars), do:  "<a>#{chars}</a>"
  def edit(:reserved_atom, chars), do:  "<a style='color:#2a6edb;'>#{chars}</a>"
  def edit(:reserved_operator, chars), do:  "<a style='color:violet;'>#{chars}</a>"
  def edit(:reserved_fn, chars), do:  "<a style='color:violet;'>#{chars}</a>"
  def edit(:reserved_block, chars), do:  "<a style='color:violet;'>#{chars}</a>"
  def edit(:reserved_general, chars), do:  "<a style='color:violet;'>#{chars}</a>"
  def edit(:operator, chars), do:  "<a style='color:red;'>#{chars}</a>"
end
